### ISSUE TITLE
Centos7.4 安装mongodb3.6

### ISSUE THREAD

**Issue by solocao** [solocao/aliyun-abc#12]
Centos7.4 安装mongodb3.6

#### 配置MongoDB的yum源

1、系统更新一下

```
yum -y update
```

2、编辑Mongodb安装源

```
vim /etc/yum.repos.d/mongodb-org-3.6.repo
```

编辑内容如下：

```
[mongodb-org-3.6]
name=MongoDB Repository
baseurl=https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.6/x86_64/
gpgcheck=1
enabled=1
gpgkey=https://www.mongodb.org/static/pgp/server-3.6.asc
```

3、安装mongodb

```
yum install -y mongodb-org
```

4、查看mongo安装位置

 ```
whereis mongod
 ```

5、查看修改配置文件

```
 vim /etc/mongod.conf
```

#### 常用操作

1、启动mongodb 

```
systemctl start mongod.service
```

2、停止mongodb 

```
systemctl stop mongod.service
```

3、设置开机启动

```
systemctl enable mongod.service
```

#### 外网访问需要关闭防火墙

CentOS 7.0默认使用的是firewall作为防火墙，这里改为iptables防火墙。

1、关闭firewall：停止firewall

```
systemctl stop firewalld.service
```

2、 禁止firewall开机启动

```
systemctl disable firewalld.service
```

#### 启动Mongo shell

```
mongo
```

1、查看数据库

```
show dbs
```

2、设置mongodb远程访问

编辑mongod.conf注释bindIp,并重启mongodb.

```
vim /etc/mongod.conf
```

3、重启mongodb：

```
systemctl restart mongod.service
```

#### 修改mongodb配置文件

```
vim /etc/mongod.conf
```

```

systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongod.log

storage:
  dbPath: /var/lib/mongo
  journal:
    enabled: true

processManagement:
  fork: true
  pidFilePath: /var/run/mongodb/mongod.pid

net:
  port: 21111
  bindIp: 0.0.0.0

security:
  authorization: enabled
  javascriptEnabled: false
```

其中端口被修改为21111（随意），并且允许远程访问，不允许则修改bandIp为：127.0.0.1

已经启用了用户身份验证，并关闭了javascript

重启系统

```
reboot
```

#### 运行

这种方式会自动使用/etc/mongod.conf配置文件

```
service mongod start
```

新建管理员用户

```
mongo --port 21111
> use admin
> db.createUser({user:"userAdmin",pwd:"123456",roles:[{role:"userAdminAnyDatabase",db:"admin"}]})
> db.auth("userAdmin","123456")
```

新建普通用户

```
> use test
> db.createUser({user:"test",pwd:"123456",roles:[{role:"readWrite",db:"test"}]})
```

退出

```
exit
```

停止

```
mongod -f /etc/mongod.conf --shutdown
```
